# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d25d89ee41b19c907edd849b23ea5085d0e1d071755f326ed9e8628a464862be4ed0545eef93e019733de48910377a8fcb3ddbbe854bfeac02bc595b4d9946f2

test:
  secret_key_base: deacee9517c2b5e8819ea8968f45584b12f6d61754ec948ea50ab6fd982c8aeb777e87fd1879e35718578d8c7c6aa4f7e83fba13982929072b1e5b552a62ced9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
